# Generated by Django 4.1.1 on 2022-09-29 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id_clinic', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=400)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('email', models.EmailField(max_length=400)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('Num_address', models.IntegerField(blank=True)),
                ('rg', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id_specialist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorySpecialist', to='cadeMED.category')),
                ('id_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='cadeMED.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id_schedules', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cadeMED.patient')),
                ('id_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Specialist', to='cadeMED.specialist')),
            ],
            options={
                'unique_together': {('date_time', 'id_patient')},
            },
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id_historic', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.CharField(blank=True, max_length=200, null=True)),
                ('description_pain', models.TextField(blank=True, max_length=150, null=True)),
                ('local_pain', models.CharField(blank=True, max_length=100, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('id_schedules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='cadeMED.schedules')),
            ],
        ),
    ]
