# Generated by Django 4.1.1 on 2022-09-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='name',
            new_name='name_specialist',
        ),
        migrations.AlterField(
            model_name='schedules',
            name='id_specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailSpecialist', to='cadeMED.specialist'),
        ),
    ]
