# Generated by Django 4.1.2 on 2022-10-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0004_alter_clinic_cnpj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('cnpj', 'name')},
        ),
    ]
