# Generated by Django 4.1.2 on 2022-10-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0005_alter_clinic_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='id_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cadeMED.patient'),
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='id_clinic',
        ),
        migrations.AddField(
            model_name='specialist',
            name='id_clinic',
            field=models.ManyToManyField(related_name='clinics_specialist', to='cadeMED.clinic'),
        ),
    ]
