# Generated by Django 4.1.2 on 2022-10-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0008_alter_clinic_options_clinic_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
    ]
