# Generated by Django 4.1.2 on 2022-11-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0010_alter_specialist_id_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='cadeMED.category'),
        ),
    ]
