# Generated by Django 4.1.2 on 2022-11-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0011_alter_specialist_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorySpecialist', to='cadeMED.category'),
        ),
    ]
