# Generated by Django 4.1.2 on 2022-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeMED', '0012_specialist_confirmation_alter_specialist_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='schedules',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
